version: '3.8'

services:
  backend:
    build:
      context: ./PTKCRM
      dockerfile: Dockerfile
    ports:
      - "3002:3001"  
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
